package ru.kuzmenko.utils;

public enum Currency {
    EUR, GBP, JPY, AUD, CHF, CAD, DKK, LKR, TND, VND, TMT, PKR, BGN, RUB, GEL, SAR, PLN, KZT, COP,
    BHD, EGP, KRW, DZD, PAB, HKD, MAD, ZAR, IQD, BOB, KWD, THB, TWD, UZS, OMR, ILS, PEN, TJS, SEK,
    SGD, HUF, UAH, CLP, DOP, CNY, ISK, AZN, HTG, ANG, LBP, MYR, IRR, UYU, JOD, PHP, XOF, LYD, NZD,
    TRY, NGN, RSD, NOK, QAR, CZK, BYN, ARS, VES, BDT, RON, MDL, CRC, AED, IDR, MXN, AMD, PYG, BRL,
    INR, NPR, XAF, KGS
}
